/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Homepage.glb')
  return (
    <group {...props} dispose={null}>
      <group name='MONTFORT'>
        <mesh
          name='HomepagePeaks'
          castShadow
          receiveShadow
          geometry={nodes.HomepagePeaks.geometry}
          material={materials.HomepagePeaks}
          position={[149.026, 14.095, 4.235]}
          rotation={[-0.048, 0.441, -0.153]}
          scale={[7.654, 7.654, 9.185]}
        />
        <mesh
          name='HomepagePeaksBG'
          castShadow
          receiveShadow
          geometry={nodes.HomepagePeaksBG.geometry}
          material={materials.HomepagePeaks}
          position={[-201.628, -35.987, 438.015]}
          rotation={[0.943, -1.443, 0.951]}
          scale={[21.869, 21.869, 26.243]}
        />
        <mesh
          name='HomepagePeaks002'
          castShadow
          receiveShadow
          geometry={nodes.HomepagePeaks002.geometry}
          material={materials.HomepagePeaks}
          position={[90.038, 5.263, -64.187]}
          rotation={[2.876, 1.009, -2.628]}
          scale={[5.569, 5.569, 6.683]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Homepage.glb')
